KPI_DEFINITIONS = {
    "users_by_age": {
        "description": "Distribuição de usuários por faixa etária",
        "dimension": "age_group",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_annual_income": {
        "description": "Distribuição de usuários por faixa de renda",
        "dimension": "annual_income",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_brand_loyalty_score": {
        "description": "Distribuição de usuários por pontuação de lealdade à marca",
        "dimension": "brand_loyalty_score",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_browse_to_buy_ratio": {
        "description": "Distribuição de usuários por proporção de navegação para compra",
        "dimension": "browse_to_buy_ratio",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_cart_abandonment_rate": {
        "description": "Distribuição de usuários por taxa de abandono de carrinho",
        "dimension": "cart_abandonment_rate",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_country": {
        "description": "Distribuição de usuários por país",
        "dimension": "country",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_device_type": {
        "description": "Distribuição de usuários por tipo de dispositivo",
        "dimension": "device_type",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_education_level": {
        "description": "Distribuição de usuários por nível de educação",
        "dimension": "education_level",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_employment_status": {
        "description": "Distribuição de usuários por status de emprego",
        "dimension": "employment_status",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_gender": {
        "description": "Distribuição de usuários por gênero",
        "dimension": "gender",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_has_children": {
        "description": "Distribuição de usuários por presença de filhos",
        "dimension": "has_children",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_household_size": {
        "description": "Distribuição de usuários por quantidade de pessoas no domicílio",
        "dimension": "household_size",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_impulse_buying_score": {
        "description": "Distribuição de usuários por pontuação de compra impulsiva",
        "dimension": "impulse_buying_score",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_preferred_payment_method": {
        "description": "Distribuição de usuários por método de pagamento preferido",
        "dimension": "preferred_payment_method",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_preferred_payment_method_by_country": {
        "description": "Distribuição de usuários por método de pagamento preferido por país",
        "dimension": "preferred_payment_method_by_country",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_preferred_payment_method_by_age_group": {
        "description": "Distribuição de usuários por método de pagamento preferido por faixa etária",
        "dimension": "preferred_payment_method_by_age_group",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_preferred_payment_method_by_annual_income": {
        "description": "Distribuição de usuários por método de pagamento preferido por faixa de renda",
        "dimension": "preferred_payment_method_by_annual_income",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_product_category_preference": {
        "description": "Distribuição de usuários por categoria de produto preferida",
        "dimension": "product_category_preference",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_product_category_preference_by_country": {
        "description": "Distribuição de usuários por categoria de produto preferida por país",
        "dimension": "product_category_preference_by_country",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_product_category_preference_by_age_group": {
        "description": "Distribuição de usuários por categoria de produto preferida por faixa etária",
        "dimension": "product_category_preference_by_age_group",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_product_category_preference_by_annual_income": {
        "description": "Distribuição de usuários por categoria de produto preferida por faixa de renda",
        "dimension": "product_category_preference_by_annual_income",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_premium_adoption": {
        "description": "Distribuição de usuários por adesão ao plano premium",
        "dimension": "premium_adoption",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_premium_adoption_by_country": {
        "description": "Distribuição de usuários por adesão ao plano premium por país",
        "dimension": "premium_adoption_by_country",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_premium_adoption_by_age_group": {
        "description": "Distribuição de usuários por adesão ao plano premium por faixa etária",
        "dimension": "premium_adoption_by_age_group",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_premium_adoption_by_annual_income": {
        "description": "Distribuição de usuários por adesão ao plano premium por faixa de renda",
        "dimension": "premium_adoption_by_annual_income",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_neighborhood": {
        "description": "Distribuição de usuários por localização geográfica",
        "dimension": "neighborhood",
        "value_field": "value",
        "type": "distribution",
        "category": "descritivo",
    },
    "users_by_referral_count": {
        "description": "Distribuição de usuários por quantidade de referrals",
        "dimension": "referral_count",
        "value_field": "value",
        "type": "distribution",
        "category": "operacional",
    },
    "users_by_return_rate": {
        "description": "Distribuição de usuários por taxa de retorno",
        "dimension": "return_rate",
        "value_field": "value",
        "type": "distribution",
        "category": "operacional",
    },
    "users_by_social_media_influence_score": {
        "description": "Distribuição de usuários por pontuação de influência social",
        "dimension": "social_media_influence_score",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_stress_from_financial_decisions_level": {
        "description": "Distribuição de usuários por nível de stress de decisões financeiras",
        "dimension": "stress_from_financial_decisions_level",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "users_by_social_sharing_frequency": {
        "description": "Distribuição de usuários por frequência de compartilhamento social",
        "dimension": "social_sharing_frequency",
        "value_field": "value",
        "type": "distribution",
        "category": "comportamental",
    },
    "average_app_usage_frequency": {
        "description": "Média de uso da aplicação",
        "dimension": "app_usage_frequency",
        "value_field": "value",
        "type": "average",
        "category": "operacional",
    },
    "average_brand_loyalty_score": {
        "description": "Média de pontuação de lealdade à marca",
        "dimension": "brand_loyalty_score",
        "value_field": "value",
        "type": "average",
        "category": "operacional",
    },
    "average_coupon_usage_per_user": {
        "description": "Média de uso de cupons por usuário",
        "dimension": "coupon_usage_per_user",
        "value_field": "value",
        "type": "average",
        "category": "operacional",
    },
    "average_cart_abandonment_rate": {
        "description": "Média de taxa de abandono de carrinho",
        "dimension": "cart_abandonment_rate",
        "value_field": "value",
        "type": "average",
        "category": "operacional",
    },
    "average_daily_session_time": {
        "description": "Média de tempo de sessão diário",
        "dimension": "daily_session_time",
        "value_field": "value",
        "type": "average",
        "category": "estratégico",
    },
    "average_product_views_per_day": {
        "description": "Média de visualizações de produtos por dia",
        "dimension": "product_views_per_day",
        "value_field": "value",
        "type": "average",
        "category": "comportamental",
    },
    "average_purchase_conversion_rate": {
        "description": "Média de taxa de conversão de compra",
        "dimension": "purchase_conversion_rate",
        "value_field": "value",
        "type": "average",
        "category": "estratégico",
    },
    "average_referral_count": {
        "description": "Média de quantidade de referrals",
        "dimension": "referral_count",
        "value_field": "value",
        "type": "average",
        "category": "operacional",
    },
    "churn_rate": {
        "description": "Taxa de churn",
        "dimension": "churn_rate",
        "value_field": "value",
        "type": "average",
        "category": "estratégico",
    },
    "net_promoter_score": {
        "description": "Pontuação de lealdade do cliente",
        "dimension": "net_promoter_score",
        "value_field": "value",
        "type": "average",
        "category": "estratégico",
    },
    "total_users": {
        "description": "Quantidade total de usuários",
        "dimension": "total_users",
        "value_field": "value",
        "type": "average",
        "category": "descritivo",
    },
}
